use_frameworks!

target 'LithoUXComponents_Example' do
  pod 'LithoUXComponents', :path => '../'
  pod 'PlaygroundVCHelpers', git: 'https://github.com/ThryvInc/playground-vc-helpers'
  pod 'LUX/Auth', git: 'https://github.com/ThryvInc/LUX'
  pod 'LUX/Base', git: 'https://github.com/ThryvInc/LUX'
  pod 'LUX/Utilities', git: 'https://github.com/ThryvInc/LUX'
  pod 'FunNet/ReactiveSwift', git: 'https://github.com/schrockblock/funnet'
  pod 'LithoOperators', git: 'https://github.com/ThryvInc/LithoOperators'
  pod 'FlexDataSource', git: 'https://github.com/ThryvInc/flex-data-source'

  target 'LithoUXComponents_Tests' do
    inherit! :search_paths
  end
end

